# name: Hello Goodbye Workflow

# on:
#     push:

# jobs:
#   say_hello:

#     runs-on: ubuntu-latest
#     steps:
#       - name: Say Hello
#         run: echo "Hello!"

#   say_goodbye:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say Goodbye
#         run: echo "Goodbye!"


name: User action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # clone the repo
        uses: actions/checkout@v4

      - name: List files
        run: ls